services:
  - type: web
    name: churn-fastapi
    env: python
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      pip install -r backend/requirements.txt
      python -m backend.ml.train
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .
